title: Wei-Cheng Chang
email: weicheng.cmu@gmail.com
description: Applied Scientist at Amazon Search
remote_theme: BDHU/minimalist
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

social-network-links:
    github: daattali
    google-scholar: https://scholar.google.com/citations?user=nxBGx-0AAAAJ&hl=en
